name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: build-output

    - name: Build test image
    - run: docker build -f Dockerfile.test -t test .

    - name: Run tests
      run: docker run --rm test
