name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - uses: actions/download-artifact@v4
      with:
        name: build-output
    - run: dotnet test --no-build --configuration Release --verbosity normal
